site_name: Cdm2883 的个人博客
site_url: https://blog.cdms.vip
site_author: Cdm2883
site_description: 我的中文个人博客 =￣ω￣=

repo_name: Cdm2883/Blog
repo_url: https://github.com/Cdm2883/Blog
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 - 2024 Cdm2883

theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    logo: material/book-open
  # noinspection YAMLSchemaValidation
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到主题跟随系统
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view

# noinspection YAMLSchemaValidation
plugins:
  - search:
      lang:
        - zh
        - en
        - ja
      separator: '[\s\u200b\-]'
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{file}"
      archive_date_format: yyyy / MM
      categories_slugify: !!python/object/apply:ext.categories_slug.slugify {}
      categories_allowed:
        - 技术
        - 绘画
        - 日常
      categories_toc: true
  - rss:
      match_path: ^posts[\\/].*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - tags:
      tags_file: tags.md
  - statistics:
      page_read_time: false
      page_template: ../overrides/page_statistics.html
      include_path: ^posts[\\/].*
  - # noinspection SpellCheckingInspection
    git-revision-date-localized:
      type: timeago
      locale: zh
      exclude:
        - tags.md
  - meta-descriptions
  - minify:
      minify_html: true

# noinspection YAMLSchemaValidation, SpellCheckingInspection
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: 获取此部分的链接
#      slugify: !!python/object/apply:pymdownx.slugs.slugify
#        kwds:
#          case: lower


extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.zhimg.com/mathjax@3.2.2/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/md-banner.css
  - assets/stylesheets/md-search.css
  - assets/stylesheets/md-post.css

extra:
  social:
    - icon: material/rss
      link: /feed_rss_created.xml
      name: RSS 订阅
    - icon: simple/bilibili
      link: https://space.bilibili.com/481934252
      name: 哔哩哔哩
    - icon: material/qqchat
      link: https://qm.qq.com/q/PprH7UV46y
      name: 腾讯 QQ
    - icon: material/github
      link: https://github.com/Cdm2883
      name: Github
    - icon: material/email
      link: mailto:hi@cdms.vip
      name: 电子邮箱
